repos:
  - repo: git://github.com/golangci/golangci-lint
    rev: v1.43.0
    hooks:
      - id: golangci-lint
        name: golangci-lint
        description: Fast linters runner for Go.
        entry: golangci-lint run -E gofmt -E gci -E dogsled -E exhaustivestruct -E whitespace --fix
        types: [ go ]
        language: golang
        pass_filenames: false
