name: Pull Request Lint

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  title:
    name: ticket check
    runs-on: ubuntu-latest

    steps:
      - name: Check for ticket
        uses: neofinancial/ticket-check-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ticketLink: 'https://dream11.atlassian.net/browse/DX-%ticketNumber%'
          ticketPrefix: 'DX-'
          titleRegex: '^DX-(?<ticketNumber>\d+)'
          branchRegex: '^DX-(?<ticketNumber>\d+)'
          bodyRegex: 'DX-(?<ticketNumber>\d+)'
          bodyURLRegex: 'http(s?):\/\/(dream11.atlassian.net)(\/browse)\/(DX\-)(?<ticketNumber>\d+)'
